### ISSUE TITLE
granite_orm vs granite-orm

### ISSUE THREAD

**Issue by drujensen** [kemalyst/granite-orm#37]
I noticed that we have underscore for the name and then dash for the github repository.  I think it would be better to have some consistency here to make it easier to configure.

**Comment by elorest** [comment]
I agree although the convention from ruby is definitely underscores except
for urls. Crystal seems to have the same standard in the core and most of
the projects.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by drujensen** [comment]
Most of the github repos for crystal are using dashes in the project name. I would stick with that convention.

**Comment by drujensen** [comment]
Actually, I take that back. I see a mix of project names with both underscores and dashes. Hhmm.

**Comment by elorest** [comment]
I asked on 2 separate days in the crystal gitter and the consensus was
underscores although some programs do use hyphens. I believe everything in
at github.com/crystal-lang/* used underscores though. It's your project
though and either work. I've been in ruby so long that hyphens just seem
really weird to me though.


Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by drujensen** [comment]
:+1:
